data_path: 'data/box/original'
new_content: "A curious puppy peeking its head out of the box"
target_folder: "puppy"
output_path: 'results/box'
masks_dir: 'data/box/source_masks'
latents_path: 'data/box/ddim_latents'
mode: "auto"
